sudo: false
language: ruby

rvm:
- 2.7
- 2.6
- 2.5
- 2.4
- 2.3
- ruby-head
- jruby-head
- jruby-9.2.9.0
- truffleruby

matrix:
  allow_failures:
    - 2.3
    - rvm: jruby-head
    - rvm: ruby-head
    - rvm: truffleruby
#   fast_finish: true
